name: audio_player
description: AUDIO PLAYER
version: 0.0.1
homepage: https://manishtalreja.com

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  plugin:
    platforms:
      android:
        package: net.manish.audio_player
        pluginClass: AudioPlayerPlugin