name: audio_player
description: NEW AUDIO PLAYER PLUGIN
version: 0.8.1
author: MANISH MAHESH TALREJA
homepage: https://github.com/MANISH-MAHESH-TALREJA

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.manish.audio
        pluginClass: AudioPlayerPlugin
