name: pokemon
description: INDIAN INDEPENDENCE DAY

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^2.0.0
  auto_animated: ^3.0.1
  marquee_widget: ^1.2.0
  toast: ^0.3.0
  flutter_html: ^2.2.1
  modal_bottom_sheet: ^2.1.0
  avatar_glow: ^2.0.2
  url_launcher: ^6.1.5
  wallpaper_manager_flutter: ^0.0.2
  flutter_downloader: ^1.8.1
  animated_background: ^2.0.0
  audioplayers: ^1.0.1
  expandable: ^5.0.1
  esys_flutter_share_plus: ^2.1.1
  flip_card: ^0.6.0
  better_player: ^0.0.83
  animated_text_kit: ^4.2.2
  giff_dialog: ^1.0.1
  cached_network_image: ^3.2.1
  path_provider: ^2.0.11
  http: ^0.13.4
  firebase_messaging: ^12.0.1
  rflutter_alert: ^2.0.4
  permission_handler: ^10.0.0
  flutter_speed_dial: ^6.0.0
  bottom_navy_bar: ^6.0.0
  flutter_cache_manager: ^3.3.0
  in_app_update: ^3.0.0
  device_info_plus: ^4.0.1
  cross_connectivity: ^3.0.5
  contained_tab_bar_view: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf
  assets:
    - assets/images/
    - assets/audio/
