name: pokemon
description: INDIAN INDEPENDENCE DAY

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  auto_animated: ^3.2.0
  marquee_widget: ^1.2.0
  toast: ^0.3.0
  another_carousel_pro: ^1.0.2
  flutter_html: ^3.0.0-beta.2
  modal_bottom_sheet: ^3.0.0
  avatar_glow: ^3.0.1
  url_launcher: ^6.2.6
  flutter_wallpaper_manager: ^0.0.4
  flutter_downloader: ^1.11.7
  animated_background: ^2.0.0
  expandable: ^5.0.1
  wc_flutter_share: ^0.4.0 #DISCONTINUED PLUGIN - REMOVE THIS OR MIGRATE THIS TO NULL SAFETY
  flip_card: ^0.7.0
  better_player_plus: ^1.0.7
  animated_text_kit: ^4.2.2
  giffy_dialog: ^2.1.0 #REMOVE THIS OR MIGRATE THIS TO NULL SAFETY
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  http: ^1.2.1
  firebase_messaging: ^14.9.2
  rflutter_alert: ^2.0.7
  permission_handler: ^11.3.1
  flutter_speed_dial: ^7.0.0
  flutter_cache_manager: ^3.3.2
  in_app_update: ^4.2.2
  connectivity: ^3.0.6 #DISCONTINUED PLUGIN - REMOVE THIS OR MIGRATE THIS TO NULL SAFETY
  # androidversion: ^0.0.2 #REMOVE THIS OR MIGRATE THIS TO NULL SAFETY
  contained_tab_bar_view: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf
  assets:
    - assets/images/
    - assets/audio/