name: pokemon
description: INDIAN INDEPENDENCE DAY

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  auto_animated: ^3.0.0
  marquee_widget: ^1.0.0
  toast: ^0.1.5
  carousel_pro: ^1.0.0
  flutter_html: ^0.11.1
  modal_bottom_sheet: ^2.0.0
  avatar_glow: ^2.0.1
  url_launcher: ^6.0.3
  wallpaper_manager: ^1.0.10
  flutter_downloader:
    git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2
  animated_background: ^2.0.0
  audioplayer: ^0.8.1
  expandable: ^5.0.1
  wc_flutter_share: ^0.4.0
  infinite_cards: ^1.0.3
  flip_card: ^0.5.0
  better_player: ^0.0.66
  animated_text_kit: ^3.1.0
  giffy_dialog: ^1.8.0
  cached_network_image: ^3.0.0
  path_provider: ^2.0.1
  http: ^0.13.3
  firebase_messaging: ^9.1.4
  rflutter_alert: ^2.0.2
  permission_handler: ^7.1.0
  flutter_speed_dial: ^3.0.5
  bottom_navy_bar: ^6.0.0
  flutter_cache_manager: ^3.0.2
  in_app_update: ^2.0.0
  connectivity: ^3.0.3
  androidversion: ^0.0.2
  contained_tab_bar_view: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf
  assets:
    - assets/images/
    - assets/audio/