name: pokemon
description: INDIAN INDEPENDENCE DAY

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_player:
    path: ./audio_player

  shimmer: ^3.0.0
  auto_animated: ^3.2.0
  another_carousel_pro: ^1.0.2
  quds_popup_menu: ^0.0.1+1
  flutter_file_downloader: ^2.0.0-dev.1
  marquee_widget: ^1.2.0
  toast: ^0.3.0
  modal_bottom_sheet: ^3.0.0
  avatar_glow: ^3.0.1
  url_launcher: ^6.2.6
  animated_background: ^2.0.0
  expandable: ^5.0.1
  esys_flutter_share_plus: ^2.2.0
  flip_card: ^0.7.0
  better_player_plus: ^1.0.7
  animated_text_kit: ^4.2.2
  giffy_dialog: ^2.1.0
  cached_network_image: ^3.3.1
  http: ^1.2.1
  firebase_messaging: ^14.9.4
  rflutter_alert: ^2.0.7
  permission_handler: ^11.3.1
  flutter_speed_dial: ^7.0.0
  in_app_update: ^4.2.2
  cross_connectivity: ^3.2.0
  contained_tab_bar_view: ^0.8.0
  open_file: ^3.3.2
  awesome_notifications: ^0.9.3+1
  wallpaper: ^1.1.1
  searchable_listview: ^2.14.0
  firebase_core: ^2.32.0
  device_info_plus: ^10.1.0
  set_ringtone: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
  assets:
    - assets/images/
    - assets/audio/
